name: Setup job

description: Setup job

runs:
  using: 'composite'
  steps:
    - if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - if: ${{ github.event_name == 'pull_request' }}
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checkout scripts
      uses: actions/checkout@v4
      with:
        repository: joinself/ci-scripts-public
        path: .ci/scripts
    - name: Setup job
      shell: sh
      run: |
        repository=${{ github.repository }}
        echo "export CI_PROJECT_NAME=\"${repository#*/}\"" > ${GITHUB_WORKSPACE}/.ci/env
        echo "export CI_PROJECT_NAMESPACE=\"${repository%/*}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        echo "export CI_WORKDIR=\"${GITHUB_WORKSPACE}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        echo "export CI_SCRIPTS=\"${GITHUB_WORKSPACE}/.ci/scripts\"" >> ${GITHUB_WORKSPACE}/.ci/env
        echo "export CI_JOB=\"${GITHUB_JOB}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        echo "export CI_REPOSITORY=\"${GITHUB_REPOSITORY}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        echo "export CI_WORKFLOW=\"${GITHUB_WORKFLOW}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        if [ "${{github.event_name}}" = "pull_request" ]; then
          echo "export CI_REF_NAME=\"${GITHUB_HEAD_REF}\"" >> ${GITHUB_WORKSPACE}/.ci/env
          echo "export CI_COMMIT_SHA=\"${{ github.event.pull_request.head.sha }}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        else
          echo "export CI_REF_NAME=\"${GITHUB_REF_NAME}\"" >> ${GITHUB_WORKSPACE}/.ci/env
          echo "export CI_COMMIT_SHA=\"${GITHUB_SHA}\"" >> ${GITHUB_WORKSPACE}/.ci/env
        fi
        if command -v git; then
          git config --global user.name ci
          git config --global user.email ops@joinself.com
          git config --global --add safe.directory '*'
        fi
